Models/FileModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace INF_HW3.Models
{
    public class FileModel
    {
        public string FileName { get; set; }

        public string FileType { get; set; }
    }
}

Controllers/MediaController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using INF_HW3.Models;

namespace INF_HW3.Controllers
{
    public class MediaController : Controller
    {
        // GET: Media

        [HttpGet]
        public ActionResult Home()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Home(HttpPostedFileBase file, FormCollection collection) // HttpPostedFileBase is the filre we're receiving
        { //Posted info that expects to receive this data -> (HttpPostedFileBase file, string Radios)

            // Receive option from radio button using form collection
            string Radiosvalue = Convert.ToString(collection["Radios"]);

            // Check options
            if(Radiosvalue == "Document")
            {
                file.SaveAs(Path.Combine(HttpContext.Server.MapPath("~/Content/Media/Documents"), file.FileName));  // Save file to Documents folder
            }
            else if(Radiosvalue == "Image")
            {
                file.SaveAs(Path.Combine(HttpContext.Server.MapPath("~/Content/Media/Images"), file.FileName));
            }
            else if(Radiosvalue == "Video")
            {
                file.SaveAs(Path.Combine(HttpContext.Server.MapPath("~/Content/Media/Videos"), file.FileName));
            }

            return RedirectToAction("Home"); // Redirect to the default get[HttpGet] action and return view
        }
        public ActionResult Files()
        {
            List<FileModel> files = new List<FileModel>();
            //  List of FileModel objects that is read from system memory 
            string[] Documents = Directory.GetFiles(Server.MapPath("~/Content/Media/Documents")); // Map path in relation to server
            string[] Images = Directory.GetFiles(Server.MapPath("~/Content/Media/Images"));
            string[] Videos = Directory.GetFiles(Server.MapPath("~/Content/Media/Videos"));

            // Populate List
            foreach (var file in Documents) // for each file found in documents
            {
                FileModel foundFile = new FileModel(); // create new FileModel object
                foundFile.FileName = Path.GetFileName(file); // set it's name
                foundFile.FileType = "doc";
                files.Add(foundFile);// Add foundFile object to files list
            }

            foreach (var file in Images) // for each file found in documents
            {
                FileModel foundFile = new FileModel(); // create new FileModel object
                foundFile.FileName = Path.GetFileName(file); // set it's name
                foundFile.FileType = "img";
                files.Add(foundFile);// Add foundFile object to files list
            }

            foreach (var file in Videos) // for each file found in documents
            {
                FileModel foundFile = new FileModel(); // create new FileModel object
                foundFile.FileName = Path.GetFileName(file); // set it's name
                foundFile.FileType = "vid";
                files.Add(foundFile);// Add foundFile object to files list
            }
            return View(files); // Sends files to view, gets received in Files.cshtml
        }

        public FileResult DownloadFile(string filename, string filetype)
        {
            byte[] bytes = null;

            if(filetype == "doc") // check what filetype is before populating
            {
                bytes = System.IO.File.ReadAllBytes(Server.MapPath("~/Content/Media/Documents/") + filename);// build file path
            }
            else if (filetype == "img") // check what filetype is before populating
            {
                bytes = System.IO.File.ReadAllBytes(Server.MapPath("~/Content/Media/Images/") + filename);
            }
            else
            {
                bytes = System.IO.File.ReadAllBytes(Server.MapPath("~/Content/Media/Videos/") + filename);
            }
            // read file I want to download

            return File(bytes, "application/octet-stream", filename);
        }

        public ActionResult DeleteFile(string filename, string filetype)
        {
            string filepath = null;
            if(filetype == "doc")
            {
                filepath = Server.MapPath("~/Content/Media/Documents/") + filename; // Directory if document
            }
            else if (filetype == "img")
            {
                filepath = Server.MapPath("~/Content/Media/Images/") + filename;
            }
            else
            {
                filepath = Server.MapPath("~/Content/Media/Videos/") + filename;
            }

            System.IO.File.Delete(filepath);
            return RedirectToAction("Home");
        }

        public ActionResult Images()
        {
            List<FileModel> Images = new List<FileModel>(); // Instantiate list of FileModel objects

            string[] Imagepaths = Directory.GetFiles(Server.MapPath("~/Content/Media/Images"));

            foreach (var file in Imagepaths)
            {
                FileModel foundFile = new FileModel(); // create new file object for each image in Imagepaths
                foundFile.FileName = Path.GetFileName(file);
                foundFile.FileType = "img";
                Images.Add(foundFile); // Add to Images list
            }

            return View(Images); // Return Image list to view
        }
        public ActionResult Videos()
        {
            List<FileModel> Videos = new List<FileModel>(); // Instantiate list of FileModel objects

            string[] Videopaths = Directory.GetFiles(Server.MapPath("~/Content/Media/Videos"));

            foreach (var file in Videopaths)
            {
                FileModel foundFile = new FileModel(); // create new file object for each video in Videopaths
                foundFile.FileName = Path.GetFileName(file);
                foundFile.FileType = "vid";
                Videos.Add(foundFile); // Add to Videos list
            }

            return View(Videos); // Return Video list to view
        }
        public ActionResult AboutMe()
        {
            return View();
        }
    }
}

Views/Media/AboutMe.cshtml
@{
    ViewBag.Title = "AboutMe";
}
<div class="container-fluid">
    <h2>Something about Amber-Leigh</h2>
    <h5>About me</h5>
</div>
<br />
<div class="container-fluid">

    <div class="row">
        <div class="col-lg-8">
            <h2>Biography</h2>
            <p>Hi my name is Amber-Leigh Lezar! I'm currently a student at the University of Pretoria and I'm studying Information and Knowledge Systems. I enjoy web design so I'm having a lot of fun with my INF module.</p>
            <p>Vivamus dolor ligula, dictum a ante eu, consectetur mollis urna. Vestibulum ultrices tellus sed nibh feugiat iaculis. Duis elementum mauris sit amet efficitur gravida. Donec a dui venenatis, tristique neque eu, hendrerit ipsum. Nam auctor turpis ut fermentum hendrerit. Aliquam erat volutpat. Etiam metus leo, scelerisque eget tempor eu, tempus eget sapien. Phasellus id varius turpis, vel fermentum enim.</p>
            <p>Etiam in tempus nisl. Phasellus consectetur augue eget leo tristique, eu elementum magna dictum. In efficitur maximus sem, ac rhoncus sem blandit at. Sed ut sagittis magna. Sed tempus sapien in leo sollicitudin, id volutpat diam fermentum.</p>
        </div>
        <div class="col-lg-4">
            <img src="~/Content/Media/Images/Me.jpg" class="img-responsive">
        </div>
    </div>
</div>

Views/Media/Files.cshtml
@model List<INF_HW3.Models.FileModel>   /*Global model object*/

@{
    ViewBag.Title = "Files";
}

<div class="container-fluid">
    <h2>Documents of any file type</h2>
    <h5>Download Documents</h5>
</div>
<br />
<div class="container-fluid">

    <div class="row">
        <div class="col-lg-12">
            <table class="table">
                <thead>
                    <tr style="background-color:black; color:white">
                        <th>File Name</th>
                        <th>Download Option</th>
                        <th>Delete Option</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var file in Model) // access list of FileModels
                    {
                    <tr>
                        <td>@file.FileName</td>
                        <td><button class="btn btn-success" onclick="window.location.href='@Url.Action("DownloadFile", "Media", new { filename = file.FileName, filetype = file.FileType })'">Download</button></td> <!-- Inject razor that will do download when clicked-->
                        <!-- Will go to DownloadFile in Media and try and send the fileName there-->
                        <td><button class="btn btn-danger" onclick="window.location.href='@Url.Action("DeleteFile", "Media", new { filename = file.FileName, filetype = file.FileType })'">Delete</button></td>
                    </tr>
                    }
                </tbody>
            </table>

        </div>
    </div>
</div>

Views/Media/Home.cshtml
@{
    ViewBag.Title = "Home";
}
<div class="container-fluid">
    <h2>My Home Page</h2>
    <h5>Sub-heading for home</h5>
</div>
<br />
<div class="container-fluid bg-info">

    <div class="row">
        <div class="col-lg-8">
            <h2>Description</h2>
            <p>Etiam in tempus nisl. Phasellus consectetur augue eget leo tristique, eu elementum magna dictum. In efficitur maximus sem, ac rhoncus sem blandit at. Sed ut sagittis magna. Sed tempus sapien in leo sollicitudin, id volutpat diam fermentum. Ut at erat at nisl finibus finibus. Phasellus placerat tellus non mi malesuada, quis aliquet risus laoreet. Praesent bibendum velit et laoreet facilisis. Donec lobortis magna metus, non pharetra metus mattis vehicula. Nullam commodo magna eget tellus maximus placerat ac quis nisl. Morbi dignissim diam quis ante pulvinar pharetra. Aliquam dictum ut nulla quis posuere. Morbi aliquam ipsum gravida velit fringilla pellentesque.</p>
            <p>Vivamus dolor ligula, dictum a ante eu, consectetur mollis urna. Vestibulum ultrices tellus sed nibh feugiat iaculis. Duis elementum mauris sit amet efficitur gravida. Donec a dui venenatis, tristique neque eu, hendrerit ipsum. Nam auctor turpis ut fermentum hendrerit. Aliquam erat volutpat. Etiam metus leo, scelerisque eget tempor eu, tempus eget sapien. Phasellus id varius turpis, vel fermentum enim.</p>
        </div>

        @using (Html.BeginForm("Home", "Media", FormMethod.Post, new { enctype = "multipart/form-data" })) //enctype needed for file upload, means it contains more than just text
        {
            <div class="col-lg-4">
                <h2>Option Selection</h2>
                <div>
                    <div class="form-check">
                        <input class="form-check-input" type="radio" name="Radios" id="DocumentRadio" value="Document">
                        <label class="form-check-label" for="DocumentRadio">
                            Document
                        </label>
                    </div>
                    <div class="form-check">
                        <input class="form-check-input" type="radio" name="Radios" id="ImageRadio" value="Image">
                        <label class="form-check-label" for="ImageRadio">
                            Image
                        </label>
                    </div>
                    <div class="form-check">
                        <input class="form-check-input" type="radio" name="Radios" id="VideoRadio" value="Video">
                        <label class="form-check-label" for="VideoRadio">
                            Video
                        </label>
                    </div>
                </div>
                <br />
                <input type="file" class="form-control" name="file" />
                <br />
                <button type="submit" class="btn btn-primary">Submit</button>
            </div>
        }
    </div>
</div>

Views/Media/Images.cshtml
@model List<INF_HW3.Models.FileModel>   /*Global model object*/

@{
    ViewBag.Title = "Files";
}

<div class="container-fluid">
    <h2>Images of any file type</h2>
    <h5>Download Images</h5>
</div>
<br />
<div class="container-fluid">
    <div class="row">
        @foreach (var file in Model) // access list of FileModels
        {
            <div class="col-lg-4">
                <div class="card" style="width: 20rem;">
                    <a href = "@Url.Content("~/Content/Media/Images/" + @file.FileName)">
                        <img class="gallery card-img-top img-rounded" height="210" width="300" src="~/Content/Media/Images/@file.FileName" alt="Card image cap">
                    </a>
                    <div class="card-body">
                        <h5 class="card-title">@file.FileName</h5>
                        <button class="btn btn-success" onclick="window.location.href='@Url.Action("DownloadFile", "Media", new { filename = file.FileName, filetype = file.FileType })'">Download</button>
                        <button class="btn btn-danger" onclick="window.location.href='@Url.Action("DeleteFile", "Media", new { filename = file.FileName, filetype = file.FileType })'">Delete</button>
                    </div>
                </div>
                <br />
            </div>
        }
    </div>
</div>

Views/Media/Videos.cshtml
@model List<INF_HW3.Models.FileModel>   /*Global model object*/

@{
    ViewBag.Title = "Files";
}

<div class="container-fluid">
    <h2>Video Files</h2>
    <h5>Download Videos</h5>
</div>
<br />
<div class="container-fluid">
    <div class="row">
        @foreach (var file in Model) // access list of FileModels
        {
            <div class="col-lg-4">
                <div class="card" style="width: 20rem;">
                    <a href="@Url.Content("~/Content/Media/Videos/" + @file.FileName)">
                        <video class="gallery card-img-top img-rounded" height="210" width="300" src="~/Content/Media/Videos/@file.FileName" alt="Card image cap">
                    </a>
                    <div class="card-body">
                        <h5 class="card-title">@file.FileName</h5>
                        <button class="btn btn-success" onclick="window.location.href='@Url.Action("DownloadFile", "Media", new { filename = file.FileName, filetype = file.FileType })'">Download</button>
                        <button class="btn btn-danger" onclick="window.location.href='@Url.Action("DeleteFile", "Media", new { filename = file.FileName, filetype = file.FileType })'">Delete</button>
                    </div>
                </div>
                <br />
            </div>
        }
    </div>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/fancybox/3.5.7/jquery.fancybox.css" integrity="sha512-nNlU0WK2QfKsuEmdcTwkeh+lhGs6uyOxuUs+n+0oXSYDok5qy0EI0lt01ZynHq6+p/tbgpZ7P+yUb+r71wqdXg==" crossorigin="anonymous" referrerpolicy="no-referrer" />
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("HOME", "Home", "Media", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Files", "Files", "Media")</li>
                    <li>@Html.ActionLink("Images", "Images", "Media")</li>
                    <li>@Html.ActionLink("Videos", "Videos", "Media")</li>
                    <li>@Html.ActionLink("About Me", "AboutMe", "Media")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)

    <script src="https://cdnjs.cloudflare.com/ajax/libs/fancybox/3.5.7/jquery.fancybox.min.js" integrity="sha512-uURl+ZXMBrF4AwGaWmEetzrd+J5/8NRkWAvJx5sbPSSuOb0bZLqf+tOzniObO00BjHa/dD7gub9oCGMLPQHtQA==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <script>
        $(document).ready(function ($) {
            $(".gallery a").fancybox();
        });
    </script>
</body>
</html>